- name: Setting up backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable default nodejs version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable Node js 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: Install Nodejs 20 version
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - nodejs
    - mysql 
    
  - name: create expense user
    ansible.builtin.user:
      name: expense

  - name: create app directory
    ansible.builtin.file:
      path: /app/backend
      state: directory

  - name: Unarchive app code that needs to be downloaded
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /app/backend
      remote_src: yes

  - name: Install packages based on package.json
    community.general.npm:
      path: /app/
      state: installed