- name: Expense app DB server setup
  hosts: db
  become: yes
  tasks:
  - name: install mysay server
    ansible.builtin.dnf:
    name: mysql
    state: present
  
  - name: state and enable mysql service
    ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: yes

  - name: set root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
    register: output

  - name: check output of setting password
    ansible.builtin.debug:
      msg: "Output is {{output}}"