- name: Expense app DB server setup
  hosts: db
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: install Python dependencies
    ansible.builtin.pip:
      name: "{{ item }}"
      state: latest
    loop:
      - cryptography
      - PyMySQL

    

  - name: state and enable mysqld service
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes

  - name: DB connection check
    community.mysql.mysql_info:
      login_user: root
      login_password: "ExpenseApp@1"
      login_host: "172.31.25.29"
      filter: version
    ignore_errors: yes
    register: mysql_output

  - name: print Db connection output
    ansible.builtin.debug:
      msg: "MYSQL Output is {{mysql_output}}"

  - name: set root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
    register: output
    when:
      mysql_output.connector_version!=0

  - name: check output of setting password
    ansible.builtin.debug:
      msg: "Output is {{output}}"