- name: Expense app DB server setup
  hosts: db
  become: yes
  vars:
    DB_IP: 172.31.26.62
  vars_prompt:
  - name: PASSWORD
    prompt: Please enter root user password
    private: false
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: install Python dependencies
    ansible.builtin.pip:
      name: "{{ item }}"
      state: latest
    loop:
      - cryptography
      - PyMySQL

  - name: state and enable mysqld service
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes

  - name: DB connection check
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ PASSWORD }}"
      login_host: "{{ DB_IP }}"
      filter: version
    ignore_errors: yes
    register: mysql_output

  - name: print Db connection output
    ansible.builtin.debug:
      msg: "MYSQL Output is {{mysql_output}}"

  - name: set root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ PASSWORD }}"
    register: output
    when:
      mysql_output.failed is true

  # - name: check output of setting password
  #   ansible.builtin.debug:
  #     msg: "Output is {{output}}"